### ISSUE TITLE
Hanging border In tablet resolution and inconsistent border radius in cost table

### ISSUE THREAD

**Issue by irajsuhail** [pupilfirst/wd.pupilfirst.org#1]
## ISSUE

The table for the cost section has two issues;
1. Unnecessary border-bottom
2. Inconsistent border radius.

![Screenshot from 2021-11-23 20-49-38](https://user-images.githubusercontent.com/26390669/143069641-89d352b6-36c8-413e-b543-845e81c0e7df.png)

**Comment by vinutv** [comment]
Fixed #2
